# Generated by Django 6.0.1 on 2026-05-21 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together={('student', 'quiz')},
        ),
    ]
