# Generated by Django 5.2.5 on 2026-01-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
