# Generated by Django 6.0.1 on 2026-01-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_instructor_alter_enrollment_course_and_more'),
        ('notes', '0002_rename_created_at_note_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.course'),
        ),
    ]
