# Generated by Django 6.0.1 on 2026-02-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_course'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='videos.video'),
        ),
    ]
