# Generated by Django 6.0.1 on 2026-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, help_text='AI ले पढ्नको लागि यहाँ नोटको टेक्स्ट पेस्ट गर्नुहोस्', null=True),
        ),
    ]
