# Generated by Django 5.2.5 on 2026-01-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_enrollment_progress_liveclass_delete_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveClass',
        ),
    ]
